name: Build for Windows, Linux And MacOs

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  CI: false

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Build Minotaur App
        uses: ./.github/actions/prepare
        with:
          working-directory: '.'
          node-version: '22.18'

      - name: Publish @minotaur-ergo/icons package
        shell: bash
        run: node cli/release.js packages/icons
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish @minotaur-ergo/ergo-lib package
        shell: bash
        run: node cli/release.js packages/icons
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
