name: Build for All platforms
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Remove old package-lock file
        run: rm package-lock.json

      - name: Install app dependencies
        run: npm install

      - name: Print package.lock file
        run: cat package-lock.json

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Update package.json files
        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'

      - name: Build Minotaur JS app and update capacitor
        run: CI=false npm run sync

      - name: Build Electron
        working-directory: ./electron
        run: CI=false; npm i; npm run build; npm run electron:pack; npm run electron:make

      - name: List outputs
        run: ls ./electron/dist

      - name: Upload Executable File to release
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/minotaur-wallet*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAP_LOGIN }}

      - name: Upload to snapstore
        run: snapcraft upload --release stable electron/dist/minotaur-wallet*.snap
#
#
#  release-mac:
#    runs-on: macos-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v1
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: 16.x
#
#      - name: Remove old package-lock file
#        run: rm package-lock.json
#
#      - name: Install app dependencies
#        run: npm install
#
#      - name: Extract version from tag
#        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
#
#      - name: Update package.json files
#        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
#
#      - name: Build Minotaur JS app
#        run: CI=false npm run sync
#
#      - name: Build Electron
#        working-directory: ./electron
#        run: CI=false; npm i; npm run build; npm run electron:pack; npm run electron:make
#
#      - name: Upload Executable File to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: electron/dist/minotaur-wallet*.dmg
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        if: startsWith(github.ref, 'refs/tags/')
#  release-windows:
#    runs-on: windows-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v1
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: 16.x
#
#      - name: Remove old package-lock file
#        run: rm package-lock.json
#
#      - name: Install app dependencies
#        run: npm install
#
#      - name: Extract version from tag
#        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
#
#      - name: Update package.json files
#        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
#
#      - name: Build Minotaur JS app
#        run: $env:CI=$false; npm run sync
#
#      - name: Build Electron
#        working-directory: ./electron
#        run: $env:CI=$false; npm i; npm run build; npm run electron:pack; npm run electron:make
#
#      - name: Upload Executable File to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: electron/dist/minotaur-wallet*.exe
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        if: startsWith(github.ref, 'refs/tags/')
#  release-android:
#    name: Release Apk for android
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout source
#        uses: actions/checkout@v2
#
#      - name: Setup java
#        uses: actions/setup-java@v1
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#
#      - name: Extract version from tag
#        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: 16.x
#
#      - name: Install app dependencies
#        run: npm install
#
#      - name: Update package.json files
#        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
#
#      - name: Build Minotaur JS app
#        run: CI=false npm run sync
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./android/gradlew
#
#      - name: Setup Android build environment
#        uses: android-actions/setup-android@v2.0.2
#
#      - name: Update AndroidManifest.xml
#        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
#        with:
#          android-manifest-path: './android/app/src/main/AndroidManifest.xml'
#          version-code: ${{ env.NUMBER_OF_COMMITS }}
#          version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
#          print-file: true
#
#      - name: Update gradle version for Android
#        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
#        with:
#          build-gradle-path: './android/app/build.gradle'
#          version-code: ${{ env.NUMBER_OF_COMMITS }}
#          version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
#          print-file: true
#
#      - name: Build app bundle
#        working-directory: android
#        run: ./gradlew clean app:assembleRelease
#
#      - uses: r0adkll/sign-android-release@v1
#        name: Sign app APK
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: android/app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
#          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
#          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
#
#      - name: move apk to root directory
#        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} minotaur-wallet-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.apk
#
#      - name: Upload Apk File to release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: minotaur-wallet-*.apk
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        if: startsWith(github.ref, 'refs/tags/')
